### ISSUE TITLE
i dont understand how to start it?

### ISSUE THREAD

**Issue by cactiham** [CodeCarbon/Roblox-Ally-Bot#1]
what does node . mean?

**Comment by CodeCarbon** [comment]
oh...
contact me on discord _mrunknown_

**Comment by CodeCarbon** [comment]
Node  is a JavaScript runtime built on Chrome's V8 JavaScript engine.

**Comment by iknotank** [comment]
can i contact u on dc?

**Comment by CodeCarbon** [comment]
sure

**Comment by cactiham** [comment]
hello i dont check github a lot anyways i cant add you
